### ISSUE TITLE
Popup broken

### ISSUE THREAD

**Issue by inakiabt** [wenzhixin/github-news-feed#8]
Since last week, the popup is broken to me:
![image](https://user-images.githubusercontent.com/606852/31669342-371523dc-b32b-11e7-8846-5b64bf20bc51.png)

**Comment by wenzhixin** [comment]
Fixed this problem.

**Comment by inakiabt** [comment]
It's better, I'm getting number of new items, but I'm still seeing issues:

![image](https://user-images.githubusercontent.com/606852/31723795-342cd2ac-b3f6-11e7-9914-55912db6b0c4.png)

**Comment by wenzhixin** [comment]
What's version? You can update it manually.
![image](https://user-images.githubusercontent.com/2117018/31725574-49822690-b3ea-11e7-8976-b5c6ff8281f2.png)

**Comment by inakiabt** [comment]
![image](https://user-images.githubusercontent.com/606852/31725653-4408fb2e-b3fb-11e7-95ae-8c82ed7a6d18.png)

This is my https://github.com/dashboard/index/1 HTML body: https://pastebin.com/EN71fbyK

**Comment by wenzhixin** [comment]
Maybe it is cache problem? Please try to right click the icon and click the last item:
![image](https://user-images.githubusercontent.com/2117018/31727392-14950416-b3ef-11e7-9589-98c7c74b2bba.png)
![image](https://user-images.githubusercontent.com/2117018/31727461-3aeec14c-b3ef-11e7-9fc1-27c3b06e2b44.png)

**Comment by wenzhixin** [comment]
Please help to right click the icon and click the last item, and then show me the html, for example:
![image](https://user-images.githubusercontent.com/2117018/31727737-fc66c1da-b3ef-11e7-8b56-e8628ce01f55.png)

**Comment by inakiabt** [comment]
I'm seeing a very different elements tree:
![image](https://user-images.githubusercontent.com/606852/31728039-9da15d7e-b401-11e7-8a7e-a1b7ddbe9035.png)

It's https://github.com/dashboard/index/1, right?

BTW, I've disabled all Github extensions (Octotree, Highlight, etc.)

**Comment by wenzhixin** [comment]
I mean right click this icon:
![image](https://user-images.githubusercontent.com/2117018/31729136-c5e3f4e4-b3f3-11e7-8d00-6696dcfc98ee.png)

**Comment by inakiabt** [comment]
![image](https://user-images.githubusercontent.com/606852/31731203-ab2254e0-b40a-11e7-9491-af805e988afa.png)

**Comment by wenzhixin** [comment]
Updated to v1.1.0

**Comment by inakiabt** [comment]
Thanks!

![image](https://user-images.githubusercontent.com/606852/31787991-b6f6c7cc-b4e3-11e7-963b-f0ec23ae2f14.png)
